# Generated by Django 5.1.6 on 2025-02-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created',
            new_name='created_at',
        ),
    ]
